# Generated by Django 2.1.7 on 2020-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0034_auto_20190222_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorproduct',
            name='id_product',
        ),
        migrations.RemoveField(
            model_name='match',
            name='id_product',
        ),
        migrations.RemoveField(
            model_name='myproduct',
            name='id_product',
        ),
        migrations.AlterField(
            model_name='match',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='При добавлении нового сравнения вручную дата добавляется автоматически.', null=True, verbose_name='Дата сравнения'),
        ),
    ]
