# Generated by Django 2.1.7 on 2020-05-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mon_app', '0035_auto_20200420_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorproduct',
            name='shop',
            field=models.CharField(blank=True, choices=[('Alser', 'Alser'), ('Sulpak', 'Sulpak'), ('Mechta', 'Mechta')], max_length=30, null=True, verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='match',
            name='shop_competitor',
            field=models.CharField(blank=True, choices=[('Alser', 'Alser'), ('Sulpak', 'Sulpak'), ('Mechta', 'Mechta')], max_length=30, null=True, verbose_name='Конкурент'),
        ),
    ]
